In [1]:
import random
random.randint(50,100)

82

In [5]:
import numpy as np
#50學生,5個分數
scores = np.random.randint(50, 101,size=(50,5))
scores

array([[ 68,  94,  66,  93,  83],
       [ 78,  52,  58,  69,  62],
       [ 55,  64,  81,  75,  91],
       [ 51,  98,  52,  58,  90],
       [ 94,  94,  59,  62,  55],
       [ 58,  91,  52,  96,  63],
       [ 54,  90,  62,  85,  99],
       [ 87,  63,  59,  65,  54],
       [ 71,  70,  95,  65,  84],
       [ 52,  91,  54,  65,  96],
       [ 61,  51,  74,  79,  82],
       [ 63,  82,  68,  69,  70],
       [ 84,  98,  91,  99,  93],
       [ 67,  93,  58,  72,  75],
       [ 95,  67,  55,  92,  78],
       [100, 100,  83,  52,  82],
       [ 92,  75,  97,  98,  92],
       [ 70,  94,  61,  87,  62],
       [ 84,  95,  88,  86,  72],
       [ 70,  98,  88, 100,  50],
       [ 59,  75,  67,  64,  51],
       [ 78,  68,  69,  68,  51],
       [ 59,  71,  83,  95,  91],
       [ 89,  60,  93,  94,  57],
       [ 51,  80,  68,  87,  97],
       [ 58,  66,  57,  91,  99],
       [ 55,  72,  79,  89, 100],
       [ 74,  68,  85,  59,  82],
       [ 94,  70,  54,  80,  87],
       [ 74,  

In [6]:
scores[0]

array([68, 94, 66, 93, 83])

In [7]:
scores[0:3]

array([[68, 94, 66, 93, 83],
       [78, 52, 58, 69, 62],
       [55, 64, 81, 75, 91]])

In [8]:
scores[0:3,0]

array([68, 78, 55])