In [1]:
import numpy as np
#50學生,5個分數
scores = np.random.randint(50, 101,size=(3,5))
scores

array([[99, 92, 61, 71, 96],
       [81, 96, 97, 84, 50],
       [59, 67, 80, 66, 79]])

In [3]:
#numpy 統計
np.sum(scores[0])
np.average(scores[0])

83.8

In [6]:
for i in scores:
    print(i)

[99 92 61 71 96]
[81 96 97 84 50]
[59 67 80 66 79]


In [7]:
scores.dtype

dtype('int64')

In [12]:
import pandas as pd

df = pd.DataFrame(data=scores,columns=['國文','英文','數學','地理','歷史'],index=['徐國堂','張xx','王xx'])
df

國文  英文  數學  地理  歷史
徐國堂  99  92  61  71  96
張xx  81  96  97  84  50
王xx  59  67  80  66  79

In [13]:
df.values

array([[99, 92, 61, 71, 96],
       [81, 96, 97, 84, 50],
       [59, 67, 80, 66, 79]])